### ISSUE TITLE
Port Error on the Elm packages website 

### ISSUE THREAD

**Issue by newtriks** [ThomasWeiser/elmfire-extra#1]
Thank you for your library. I just thought I'd point out that on http://package.elm-lang.org/packages/ThomasWeiser/elmfire-extra/1.0.0 it is throwing the following error:

```
Port Error:

    Regarding the port named 'context' with type:

        Page.Package.Context

    You just sent the value:

        {"user":"ThomasWeiser","project":"elmfire-extra","version":"1.0.0","allVersions":["1.0.0"],"moduleName":null}

    but it cannot be converted to the necessary type.
    Runtime error when sending values through a port.
    Expecting an object with fields `user`, `name`, `version`, `versionList` but was given
    {"user":"ThomasWeiser","project":"elmfire-extra","version":"1.0.0","allVersions":["1.0.0"],"moduleName":null}

Open the developer console for more details.
```

**Comment by ThomasWeiser** [comment]
I think this was just a temporarily problem while the package site has been updated by Evan.
It's working for me now. Maybe you have to clear your browser cache.

Please let me know if the error continues to crop up.

**Comment by ThomasWeiser** [comment]
See also: [Elm-lang.org packages down](https://groups.google.com/forum/#!topic/elm-discuss/LwqoKclwknc)
