### ISSUE TITLE
Basic Example

### ISSUE THREAD

**Issue by raineorshine** [ThomasWeiser/elmfire-extra#4]
I'm struggling getting a basic version working. I can follow the [TodoMVC](https://github.com/ThomasWeiser/todomvc-elmfire) example, but it's still complicated for me, so I'm trying to build something simpler that is closer to my existing architecture.

Any idea why this code doesn't work? I'm probably missing something critical but I'm not enough with Elm to not really now what it i

Thanks for your help!

```
import Html exposing (..)
import Html.Events exposing (onClick)
import Json.Decode as JD exposing ((:=))
import Json.Encode as JE
import Dict exposing (Dict)
import ElmFire
import ElmFire.Dict
import ElmFire.Op

url = "https://elmzones.firebaseio.com"

config = {
    location = ElmFire.fromUrl url,
    orderOptions = ElmFire.noOrder,
    encoder = JE.string,
    decoder = JD.string
  }

(subscriptionTask, serverLabel) = ElmFire.Dict.mirror config

type alias Model = String

type Action =
  NoOp
  | ServerUpdate (Dict String String)

startModel = "Waiting..."

actions : Signal.Mailbox Action
actions =
  Signal.mailbox NoOp

model : Signal Model
model =
  Signal.foldp update startModel (Signal.merge
    actions.signal
    (Signal.map ServerUpdate serverLabel))

view : Signal.Address Action -> Model -> Html
view address name =
  h1 [] [ text name ]

update : Action -> Model -> Model
update action model =
  case action of
    NoOp -> model
    ServerUpdate dict -> "Updated"

main : Signal Html
main =
  Signal.map (view actions.address) model
```

**Comment by raineorshine** [comment]
FYI, I'm changing the Firebase value directly in the Firebase interface and expecting to see "Waiting..." change to "Updated."

**Comment by ThomasWeiser** [comment]
It's all fine except that you have to actually run the `subscriptionTask` returned by `ElmFire.Dict.mirror`. To do so hand the task over to an outgoing port like this:

``` elm
...
import Task exposing (Task)
...
(subscriptionTask, serverLabel) = ElmFire.Dict.mirror config

port runSubscriptionTask :  Task ElmFire.Error (Task ElmFire.Error ())
port runSubscriptionTask = subscriptionTask
```

**Comment by raineorshine** [comment]
It works!!! Thank you. I am not familiar with ports.

Out of curiosity, is there a reason that the port is necessary, instead of just having a signal that is ready to go?

I am thinking my example might be nice for other beginners as a stepping stone to the TodoMVC example you built. If I create a repo for it, would you be open to a pull request that includes a link on the README here?

**Comment by raineorshine** [comment]
https://github.com/metaraine/elmfire-extra-hello-world

**Comment by ThomasWeiser** [comment]
The task to initiate the mirroring is necessary because in Elm every function is pure without side effects. For something to be effectfull you have to pass it to a port (or as the result of main in case of Html).

So, `ElmFire.Extra.mirror` in itself is a pure function. Its effect is executed only after passing the resulting task to a port..

I will look at your minimal example. Thanks for the offer.

**Comment by raineorshine** [comment]
FYI, I'm working on more examples that progressively build up for Elm beginners like me:

https://github.com/metaraine/elmfire-extra-example2
https://github.com/metaraine/elmfire-extra-example3

**Comment by ThomasWeiser** [comment]
I linked to your first example repo in the Readme.
Thank you for helping people to get started with elmfire-extra!

**Comment by raineorshine** [comment]
Thanks!!!
