### ISSUE TITLE
Destructured assignment is an anti-pattern?

### ISSUE THREAD

**Issue by raineorshine** [ThomasWeiser/elmfire-extra#5]
_Posted this to the Elm Slack, thought I would CC here to hear your thoughts:_

Is it possible to make type annotations for destructured assignments?

```
import Html exposing (text)

(a,b) : (String, String)
(a,b) = ("Hello", "World!")

main =
  text a
```

Gives this error:

```
SYNTAX PROBLEMjump to error
I ran into something unexpected when parsing your code!

3| (a,b) : (String, String)
I am looking for one of the following things:

    an equals sign '='
    whitespace
```

I would like a type annotation for this pattern in elmfire-extra:

```
(subscriptionTask, model) = ElmFire.Dict.mirror config
```

https://github.com/ThomasWeiser/elmfire-extra/blame/9aab79b89f9d42463505c021342812e364d50fb4/README.md#L75

(If this is not possible, would you say that returning a tuple of complex data types in this way is an anti-pattern?)

**Comment by ThomasWeiser** [comment]
You can annotate the tuple and you can annotate the individuell values, but as you noticed not at once with a destructuring definition.

Fully annotated solution:

``` elm
taskAndModel : (Task ElmFire.Error (Task ElmFire.Error ()), Signal (Dict String Element))
taskAndModel = EmFire.Extra.mirror config

subscriptionTask : Task ElmFire.Error (Task ElmFire.Error ())
subscriptionTask = fst taskAndModel

model : Signal (Dict String Element)
model = snd taskAndModel
```

**Comment by raineorshine** [comment]
Thank you, that is clear to me.

**Comment by ThomasWeiser** [comment]
I have updated the documentation to make things clearer. Thank you for pointing me to this issue!
